export default [
  {
    query: 'CYP78A7',
    queryLength: '559',
    alignments: [
      {
        subjectName: 'Ghir_D06G020210.1 unnamed protein product',
        subjectLength: '559',
        score: '1155',
        eValue: '0.0',
        positives: '99',
        pairSequence:
          'Query  1    MNPFLCFVLQAWNPSSCQVSSMETSRFLRDYAVWEINAFLWISLITITYFLSYKLFKLFK  60\n            MNPFLCFVLQAWNPSSCQVSSMETSRF RDYAVWEINAFLWISLITITYFLSYKLFKLFK\nSbjct  1    MNPFLCFVLQAWNPSSCQVSSMETSRFFRDYAVWEINAFLWISLITITYFLSYKLFKLFK  60\n\nQuery  61   LWNQACKIPGPPSPSFYGYFTTLSKQNLTEVLSDSHEEYGSIVKLWLSPKQLLVSIKEPE  120\n            LWNQACKIPGPPSPSFYGYFTTL KQNLTEVLSDSHEEYGSIVKLWLSPKQLLVSIKEPE\nSbjct  61   LWNQACKIPGPPSPSFYGYFTTLCKQNLTEVLSDSHEEYGSIVKLWLSPKQLLVSIKEPE  120\n\nQuery  121  IIKEMLLKAKDKLPLTGKAFNLAFGRSTLFASSFDKVESRRESLASELNVRLLDRANLIA  180\n            IIKEMLLKAKDKLPLTGKAFNLAFGRSTLFASSFDKVESRRESLASELNVRLLDRANLI \nSbjct  121  IIKEMLLKAKDKLPLTGKAFNLAFGRSTLFASSFDKVESRRESLASELNVRLLDRANLIP  180\n\nQuery  181  TKAVDHIMAELHQNMTKGSINCKMTSQHMAFTLLGATIFGDTFLAWLKSTIYEELLMMVA  240\n            TKAVDHIMAELHQNMTKGSINCKMTSQHMAFTLLGATIFGDTFLAWLKSTIYEELLMMVA\nSbjct  181  TKAVDHIMAELHQNMTKGSINCKMTSQHMAFTLLGATIFGDTFLAWLKSTIYEELLMMVA  240\n\nQuery  241  KDACFWASYSVIPFWKQGFWRYRRLCTELKWLTQDLVQQCSKYRQYRHMEPSANLGMEAG  300\n            KDACFWASYSVIPFWKQGFWRYRRLCTELKWLTQDLVQQCSKYRQYRHMEPSANLGMEAG\nSbjct  241  KDACFWASYSVIPFWKQGFWRYRRLCTELKWLTQDLVQQCSKYRQYRHMEPSANLGMEAG  300\n\nQuery  301  VFLQDNISLQEINGRHNVRDESCGNIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYS  360\n            VFLQDNISLQ INGRHNVRDESCGNIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYS\nSbjct  301  VFLQDNISLQVINGRHNVRDESCGNIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYS  360\n\nQuery  361  EIIMAKKGSEDKAQPVVEKMPLLWATIYESARVMPAGPLLQRCSLKHDLRLKSGVIVPAG  420\n            EIIMAKKGSEDKAQPVVEKMPLLWATIYESARVMPAGPLLQRCSLKHDLRLKSGVIVPAG\nSbjct  361  EIIMAKKGSEDKAQPVVEKMPLLWATIYESARVMPAGPLLQRCSLKHDLRLKSGVIVPAG  420\n\nQuery  421  AILVVPMQLVQTDDSSWGNDAGKFNPYRFLSKTEKTSASPNMDASIAGHAEELKDQRKCT  480\n            AILVVPMQLVQTDDSSWGNDAGKFNPYRFLSKTEKTSASPNMDASIAGHAEELKDQRKCT\nSbjct  421  AILVVPMQLVQTDDSSWGNDAGKFNPYRFLSKTEKTSASPNMDASIAGHAEELKDQRKCT  480\n\nQuery  481  FVLKDPNKNPAFLPFGSGARACVGQKFVTQGVATLFASLLEQYEVRLRSGSKTNSKPSTN  540\n            FVLKDPNKNPAFLPFGSGARACVGQKFV QGVATLFASLLEQYEVRLRSGSKTNSKPSTN\nSbjct  481  FVLKDPNKNPAFLPFGSGARACVGQKFVIQGVATLFASLLEQYEVRLRSGSKTNSKPSTN  540\n\nQuery  541  YSMSQDFLSSELVFARRNN  559\n            YSMSQDFLSSELVFARRNN\nSbjct  541  YSMSQDFLSSELVFARRNN  559\n\n',
        gaps: '0',
        identities: '99'
      },
      {
        subjectName: 'Ghir_D06G020210.2 unnamed protein product',
        subjectLength: '524',
        score: '970',
        eValue: '0.0',
        positives: '99',
        pairSequence:
          'Query  90   EVLSDSHEEYGSIVKLWLSPKQLLVSIKEPEIIKEMLLKAKDKLPLTGKAFNLAFGRSTL  149\n            EVLSDSHEEYGSIVKLWLSPKQLLVSIKEPEIIKEMLLKAKDKLPLTGKAFNLAFGRSTL\nSbjct  55   EVLSDSHEEYGSIVKLWLSPKQLLVSIKEPEIIKEMLLKAKDKLPLTGKAFNLAFGRSTL  114\n\nQuery  150  FASSFDKVESRRESLASELNVRLLDRANLIATKAVDHIMAELHQNMTKGSINCKMTSQHM  209\n            FASSFDKVESRRESLASELNVRLLDRANLI TKAVDHIMAELHQNMTKGSINCKMTSQHM\nSbjct  115  FASSFDKVESRRESLASELNVRLLDRANLIPTKAVDHIMAELHQNMTKGSINCKMTSQHM  174\n\nQuery  210  AFTLLGATIFGDTFLAWLKSTIYEELLMMVAKDACFWASYSVIPFWKQGFWRYRRLCTEL  269\n            AFTLLGATIFGDTFLAWLKSTIYEELLMMVAKDACFWASYSVIPFWKQGFWRYRRLCTEL\nSbjct  175  AFTLLGATIFGDTFLAWLKSTIYEELLMMVAKDACFWASYSVIPFWKQGFWRYRRLCTEL  234\n\nQuery  270  KWLTQDLVQQCSKYRQYRHMEPSANLGMEAGVFLQDNISLQEINGRHNVRDESCGNIMSL  329\n            KWLTQDLVQQCSKYRQYRHMEPSANLGMEAGVFLQDNISLQ INGRHNVRDESCGNIMSL\nSbjct  235  KWLTQDLVQQCSKYRQYRHMEPSANLGMEAGVFLQDNISLQVINGRHNVRDESCGNIMSL  294\n\nQuery  330  LFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKKGSEDKAQPVVEKMPLLWATIYE  389\n            LFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKKGSEDKAQPVVEKMPLLWATIYE\nSbjct  295  LFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKKGSEDKAQPVVEKMPLLWATIYE  354\n\nQuery  390  SARVMPAGPLLQRCSLKHDLRLKSGVIVPAGAILVVPMQLVQTDDSSWGNDAGKFNPYRF  449\n            SARVMPAGPLLQRCSLKHDLRLKSGVIVPAGAILVVPMQLVQTDDSSWGNDAGKFNPYRF\nSbjct  355  SARVMPAGPLLQRCSLKHDLRLKSGVIVPAGAILVVPMQLVQTDDSSWGNDAGKFNPYRF  414\n\nQuery  450  LSKTEKTSASPNMDASIAGHAEELKDQRKCTFVLKDPNKNPAFLPFGSGARACVGQKFVT  509\n            LSKTEKTSASPNMDASIAGHAEELKDQRKCTFVLKDPNKNPAFLPFGSGARACVGQKFV \nSbjct  415  LSKTEKTSASPNMDASIAGHAEELKDQRKCTFVLKDPNKNPAFLPFGSGARACVGQKFVI  474\n\nQuery  510  QGVATLFASLLEQYEVRLRSGSKTNSKPSTNYSMSQDFLSSELVFARRNN  559\n            QGVATLFASLLEQYEVRLRSGSKTNSKPSTNYSMSQDFLSSELVFARRNN\nSbjct  475  QGVATLFASLLEQYEVRLRSGSKTNSKPSTNYSMSQDFLSSELVFARRNN  524\n\n',
        gaps: '0',
        identities: '99'
      },
      {
        subjectName: 'Ghir_A06G019060.1 unnamed protein product',
        subjectLength: '372',
        score: '742',
        eValue: '0.0',
        positives: '97',
        pairSequence:
          'Query  188  MAELHQNMTKGSINCKMTSQHMAFTLLGATIFGDTFLAWLKSTIYEELLMMVAKDACFWA  247\n            MAELHQNMT+GSINCKMTSQHMAFTLLGATIFGDTFL+W KSTIYEELLMMVAKDACFWA\nSbjct  1    MAELHQNMTEGSINCKMTSQHMAFTLLGATIFGDTFLSWSKSTIYEELLMMVAKDACFWA  60\n\nQuery  248  SYSVIPFWKQGFWRYRRLCTELKWLTQDLVQQCSKYRQYRHMEPSANLGMEAGVFLQDNI  307\n            SYSVIPFWKQGFWRYRRLCTELKWLTQDL QQCSKYRQY H+EPSANLGMEAG+FLQDNI\nSbjct  61   SYSVIPFWKQGFWRYRRLCTELKWLTQDLFQQCSKYRQYHHVEPSANLGMEAGIFLQDNI  120\n\nQuery  308  SLQEINGRHNVRDESCGNIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKK  367\n            SLQEINGR NVRDESC  IMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKK\nSbjct  121  SLQEINGRLNVRDESCCTIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKK  180\n\nQuery  368  GSEDKAQPVVEKMPLLWATIYESARVMPAGPLLQRCSLKHDLRLKSGVIVPAGAILVVPM  427\n            G EDKAQPVVEKMPLL ATIYESARVMPAGPLLQRCSLKHDLRLKSGVIVPAGAILVVPM\nSbjct  181  GLEDKAQPVVEKMPLLLATIYESARVMPAGPLLQRCSLKHDLRLKSGVIVPAGAILVVPM  240\n\nQuery  428  QLVQTDDSSWGNDAGKFNPYRFLSKTEKTSASPNMDASIAGHAEELKDQRKCTFVLKDPN  487\n            QLVQTDDSSWGNDAGKFNPYRFLSKTEKTSAS NMDASIAGHAEE KDQRKCTFVLKDPN\nSbjct  241  QLVQTDDSSWGNDAGKFNPYRFLSKTEKTSASENMDASIAGHAEEHKDQRKCTFVLKDPN  300\n\nQuery  488  KNPAFLPFGSGARACVGQKFVTQGVATLFASLLEQYEVRLRSGSKTNSKPSTNYSMSQDF  547\n            KNP FLPFGSGARACV QKFV QGVATLFASLLEQYEVRLRSGSKT+SKPSTNYSMSQDF\nSbjct  301  KNPTFLPFGSGARACVCQKFVIQGVATLFASLLEQYEVRLRSGSKTDSKPSTNYSMSQDF  360\n\nQuery  548  LSSELVFARRNN  559\n            LSSELVFARRNN\nSbjct  361  LSSELVFARRNN  372\n\n',
        gaps: '0',
        identities: '95'
      },
      {
        subjectName: 'Ghir_A06G019060.2 unnamed protein product',
        subjectLength: '315',
        score: '566',
        eValue: '0.0',
        positives: '97',
        pairSequence:
          'Query  188  MAELHQNMTKGSINCKMTSQHMAFTLLGATIFGDTFLAWLKSTIYEELLMMVAKDACFWA  247\n            MAELHQNMT+GSINCKMTSQHMAFTLLGATIFGDTFL+W KSTIYEELLMMVAKDACFWA\nSbjct  1    MAELHQNMTEGSINCKMTSQHMAFTLLGATIFGDTFLSWSKSTIYEELLMMVAKDACFWA  60\n\nQuery  248  SYSVIPFWKQGFWRYRRLCTELKWLTQDLVQQCSKYRQYRHMEPSANLGMEAGVFLQDNI  307\n            SYSVIPFWKQGFWRYRRLCTELKWLTQDL QQCSKYRQY H+EPSANLGMEAG+FLQDNI\nSbjct  61   SYSVIPFWKQGFWRYRRLCTELKWLTQDLFQQCSKYRQYHHVEPSANLGMEAGIFLQDNI  120\n\nQuery  308  SLQEINGRHNVRDESCGNIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKK  367\n            SLQEINGR NVRDESC  IMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKK\nSbjct  121  SLQEINGRLNVRDESCCTIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKK  180\n\nQuery  368  GSEDKAQPVVEKMPLLWATIYESARVMPAGPLLQRCSLKHDLRLKSGVIVPAGAILVVPM  427\n            G EDKAQPVVEKMPLL ATIYESARVMPAGPLLQRCSLKHDLRLKSGVIVPAGAILVVPM\nSbjct  181  GLEDKAQPVVEKMPLLLATIYESARVMPAGPLLQRCSLKHDLRLKSGVIVPAGAILVVPM  240\n\nQuery  428  QLVQTDDSSWGNDAGKFNPYRFLSKTEKTSASPNMDASIAG  468\n            QLVQTDDSSWGNDAGKFNPYRFLSKTEKTSAS NMDASIAG\nSbjct  241  QLVQTDDSSWGNDAGKFNPYRFLSKTEKTSASENMDASIAG  281\n\n',
        gaps: '0',
        identities: '95'
      },
      {
        subjectName: 'Ghir_A12G017100.1 unnamed protein product',
        subjectLength: '519',
        score: '93.6',
        eValue: '1e-19',
        positives: '41',
        pairSequence:
          'Query  37   NAFLWISLI--TITYFLSYKLFKLFKLWNQAC-KIPGPPSPSFYGYFTTLSKQNLTEVLS  93\n             AFLW  L+  T+ ++ S       +  ++A   IPGP    F G  T  +       LS\nSbjct  18   EAFLWAVLLVGTVAFWFSPGGIAWARFRSKASFAIPGPLGFPFLGLLTVFTGSTPHRALS  77\n\nQuery  94   DSHEEYGSIVKLWLSP--KQLLVSIKEPEIIKEMLLK-AKDKLPLTGKAFNLAFGRSTLF  150\n               +   ++  +  S    + ++S  +PE  +++L   A    P+   A+ L F R+  F\nSbjct  78   KLAKTLNAVKLMAFSVGCTRFVIS-SDPETARDILNNSAFADRPVKESAYELLFHRAMGF  136\n\nQuery  151  ASSFDKVESRRESLASEL--NVRLLDRANL---IATKAVDHIMAELHQNMTKGSINCKMT  205\n            A   D     R   A+ L    R+     L   I  K  + I   +    +KG +  +  \nSbjct  137  APYGDYWRDLRRISATHLFSPKRIAGFEGLRREIGIKMGEEIKCSME---SKGEVFIRRV  193\n\nQuery  206  SQHMAFTLLGATIFGDTF-----------LAWLKSTIYEELLMMVAKDACFWASYSVIPF  254\n                + + + AT+FG  +           L  L S  YE L +    D   +    ++ F\nSbjct  194  LHLGSLSSVMATVFGKRYDFENPGLEGLQLEELVSEGYELLGIFNWSD--HFPLLGLLDF  251\n\nQuery  255  WKQGFW-RYRRLCTELKWLTQDLVQQCSKYRQYRHMEPSANLGMEAGVFLQDNISLQEIN  313\n              QG   R R L +++     +++++ +  R    +E   N   + G F+   + L++  \nSbjct  252  --QGVRKRCRILASKVNVFVSNIIEEHALKRVNGGLEDDGN---KVGDFVDVLLDLEKHE  306\n\nQuery  314  GRHNVRDESCGNIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKKGSEDKA  373\n              +N   +    +  ++F G  T   L+  +L R+V HPEIQ K  +EI    +GS+  +\nSbjct  307  KLNN--SDMIAVLWEMIFRGTDTVAILLEWILARIVLHPEIQAKAQAEIDAVVEGSKQVS  364\n\nQuery  374  QPVVEKMPLLWATIYESARVMPAGPLLQRCSLK-HDLRLKSGVIVPAGAILVVPMQLVQT  432\n               +  MP L A + E+ RV P GPLL    L  HD+ +   ++VPAG   +V M  +  \nSbjct  365  DSDIHNMPYLQAIVKETLRVHPPGPLLSWARLAIHDVHVGD-LLVPAGTTAMVNMWAITH  423\n\nQuery  433  DDSSWGNDAGKFNPYRFLSKTEKTSASPNMDASIAGHAEELKDQRKCTFVLKDPNKNPAF  492\n            ++  W  DA KF P RF+ +      S   D  +A                         \nSbjct  424  NEDVW-EDAVKFRPERFMEEEVSVMGS---DLRVA-------------------------  454\n\nQuery  493  LPFGSGARACVGQKFVTQGVATLFASLLEQYE  524\n             PFGSG R C G+      V      LL+ ++\nSbjct  455  -PFGSGRRVCPGKAMGLATVHLWLVQLLQGFK  485\n\n',
        gaps: '13',
        identities: '24'
      },
      {
        subjectName: 'Ghir_D12G017340.1 unnamed protein product',
        subjectLength: '491',
        score: '91.3',
        eValue: '8e-19',
        positives: '40',
        pairSequence:
          'Query  37   NAFLWISLI--TITYFLSYKLFKLFKLWNQAC-KIPGPPSPSFYGYFTTLSKQNLTEVLS  93\n             AFLW  L+  T+ ++ S       +  ++A   IPGP    F G  T  +        S\nSbjct  18   EAFLWAVLLVGTVAFWFSPGGIAWARFRSKASFAIPGPLGFPFLGLLTVFTG-------S  70\n\nQuery  94   DSHEEYGSIVKLWLSPKQLLVSI--------KEPEIIKEMLLK-AKDKLPLTGKAFNLAF  144\n              H     + K   + K +  S+         +PE  +++L   A    P+   A+ L F\nSbjct  71   TPHRTLAKLAKTLNAVKLMAFSVGCTRFVISSDPETARDILNNSAFADRPVKESAYELLF  130\n\nQuery  145  GRSTLFASSFDKVESRRESLASEL--NVRLLDRANL---IATKAVDHIMAELHQNMTKGS  199\n             R+  FA   D     R   ++ L    R+     L   I  K V+ I   +    +KG \nSbjct  131  HRAMGFAPYGDYWRDLRRISSTHLFSPKRIAGFEGLRREIGIKMVEEIKCSME---SKGE  187\n\nQuery  200  INCKMTSQHMAFTLLGATIFGDTFLAWLKSTIYEELLMMVAKDACFWASY----SVIPFW  255\n            +  +      + + + AT+FG          I+             W+ +     ++ F \nSbjct  188  VFIRRVLHLGSLSSVMATLFG----------IFN------------WSDHFPLLGLLDF-  224\n\nQuery  256  KQGFW-RYRRLCTELKWLTQDLVQQCSKYRQYRHMEPSANLGMEAGVFLQDNISLQEING  314\n             QG   R R L +++     +++++ +  R    +E   N   + G F+   + L++   \nSbjct  225  -QGVRKRCRNLASKVNVFVGNIIEEHALKRVNGGLEDDGN---KVGDFVDVLLDLEKHEK  280\n\nQuery  315  RHNVRDESCGNIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKKGSEDKAQ  374\n             +N   +    +  ++F G  T   L+  +L R+V HPEIQ K  +EI    +GS+  + \nSbjct  281  LNN--SDMIAVLWEMIFRGTDTVAILLEWILARIVLHPEIQAKAQAEIDAVVEGSKQVSD  338\n\nQuery  375  PVVEKMPLLWATIYESARVMPAGPLLQRCSLK-HDLRLKSGVIVPAGAILVVPMQLVQTD  433\n              +  MP L A + E+ RV P GPLL    L  HD+ +    +VPAG   +V M  +  +\nSbjct  339  SDIHNMPYLQAIVKETLRVHPPGPLLSWARLAIHDVHVGDR-LVPAGTTAMVNMWAITHN  397\n\nQuery  434  DSSWGNDAGKFNPYRFLSKTEKTSASPNMDASIAGHAEELKDQRKCTFVLKDPNKNPAFL  493\n            D  W  DA KF P RF+            + S+ G      D R                \nSbjct  398  DDVW-EDAVKFRPERFME-----------EVSVMG-----SDLR--------------LA  426\n\nQuery  494  PFGSGARACVGQKFVTQGVATLFASLLEQYE  524\n            PFGSG R C G+      V    A LL+ ++\nSbjct  427  PFGSGRRVCPGKAMGLATVHLWLAQLLKGFK  457\n\n',
        gaps: '18',
        identities: '24'
      },
      {
        subjectName: 'Ghir_D03G017150.1 unnamed protein product',
        subjectLength: '532',
        score: '89.7',
        eValue: '3e-18',
        positives: '42',
        pairSequence:
          'Query  46   TITYFLSYKLFKLFKLW--NQACKI-----PGPPSPSFYGYFTTLSKQNLTEVLSDSHEE  98\n             +++F+      L+ LW   ++ KI     PGP      GY   L   NL    ++    \nSbjct  26   VLSFFMVILAISLWHLWFVKKSKKIVAQLPPGPRGLPIVGYLPFLGTDNLHLSFTELAAT  85\n\nQuery  99   YGSIVKLWLSPKQLLVSIKEPEIIKEMLLK-----AKDKLPLTGKAFNLAFGRSTLFASS  153\n            YG I KLWL  K L V I  PE+ KE++       ++   P+  +  +         + S\nSbjct  86   YGPIFKLWLGNK-LCVVISSPELAKEVVRDHDVTFSERDPPIAAQVASFGCNDIAFDSYS  144\n\nQuery  154  FDKVESRRESLASEL--NVRLLDRANLIATKAVDHIMAELHQNMTKGSINCKMT---SQH  208\n              + +++R+ LA+EL  N R L+    +  + V + + ++++N+ K     K T   + +\nSbjct  145  NPRWKNKRKVLATELLTNAR-LNACYGLRREQVMNGLKDVYENVGKPIDIGKWTYLVALN  203\n\nQuery  209  MAFTL-LGATIFGDTFLAW---LKSTIYEELLMMVAKDACFWASYSVIPFWKQGFWR-YR  263\n            +A ++ LG  + G+   A    LK    E +++M  K        ++  F  QG  R  R\nSbjct  204  VAISMILGGELPGEKGAAIEGNLKENSSESMVLM-GKPNVSDIFPAIARFDIQGIERGMR  262\n\nQuery  264  RLCTELKWLTQDLVQ-QCSKYRQYRHMEPSANLGMEAGVFLQDNISLQEINGRHNVRDES  322\n            ++  +   L + +++    K +  +  E             ++N    E N      DE \nSbjct  263  KINQQFNRLLESVIEVAIDKEKDMKSREQKLGFLELLLHLERNN---NEDNASPLTMDEV  319\n\nQuery  323  CGNIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKKGSEDKAQPVVEKMPL  382\n             G ++ +L  G  TT  ++   +  L+ HPEI  K+  E+      +    +  +  +  \nSbjct  320  KGLVVDILVGGTDTTTTMVEWTMAVLMQHPEIMEKVKKELSDVVGVNNTVEEFHLSNLSY  379\n\nQuery  383  LWATIYESARVMPAGPLL-QRCSLKHDLRLKSGVIVPAGAILVVPMQLVQTDDSSWGNDA  441\n            L   I E+ R+ PA PLL  RC  +  + L +G  +P G+ L + M  +  D   W N  \nSbjct  380  LNVVIKETFRLHPALPLLVPRCPAR-SVHL-NGYTIPKGSRLFINMWCIHRDPRIWENPL  437\n\nQuery  442  GKFNPYRFLSKTEKTSASPNMDASIAGHAEELKDQRKCTFVLKDPNKNPAFLPFGSGARA  501\n             +F P RFL+  + ++   N             D R              F+PFGSG R \nSbjct  438  -EFRPERFLNDPDNSNHYGN-------------DFR--------------FMPFGSGRRK  469\n\nQuery  502  CVGQKFVTQGVATLFASLLEQYEVRLRSG  530\n            C G     + +  + ASLL  +E RL  G\nSbjct  470  CPGIPLGEKLLFFILASLLHSFEWRLPHG  498\n\n',
        gaps: '12',
        identities: '24'
      },
      {
        subjectName: 'Ghir_A02G014990.1 unnamed protein product',
        subjectLength: '393',
        score: '88.6',
        eValue: '3e-18',
        positives: '41',
        pairSequence:
          'Query  198  GSINCKMTSQHMAFTLLGATIFGDTFLAWLKSTIYEELLMMVAK-----------DACFW  246\n            GS+  +   Q  A   +  ++FG  +     S   EEL  MV +           D   W\nSbjct  58   GSVCLRKHLQFAALNNIMGSVFGRRYDQRKDSEELEELRDMVREGFELLGAFNWSDYLPW  117\n\nQuery  247  ASYSVIPFWKQGFWRYRRLCTELKWLTQDLVQQCSKYRQYRHMEPSANLGMEAGVFLQDN  306\n             SY   PF      R  + C +L    + LV+      Q+R +  S          L DN\nSbjct  118  LSYFYDPF------RINQRCLQLVPRVRKLVKGI--IEQHRQLSESK--------MLSDN  161\n\nQuery  307  ISLQEI----NGRHNVRDESCGNIM-SLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSE  361\n            +   ++    +G   ++++   +++  ++F G  TT  L   ++  LV HPE+Q K+  E\nSbjct  162  VDFVDVLLSLDGEEKLQEDDMVSVLWEMIFRGTDTTALLTEWVMAELVLHPEVQAKLQLE  221\n\nQuery  362  IIMAKKGSEDKAQPVVEKMPLLWATIYESARVMPAGPLLQRCSLK-HDLRLKSGVIVPAG  420\n            I  A + ++      V K+P L A + E+ R+ P GPLL    L   D++L +G++VPA \nSbjct  222  IDSATR-NKTLTDADVAKLPYLQAVVKETLRIHPPGPLLSWARLSTSDVQLSNGMLVPAN  280\n\nQuery  421  AILVVPMQLVQTDDSSWGNDAGKFNPYRFLSKTEKTSASPNMDASIAGHAEELKDQRKCT  480\n               +V M  +  D   W  D  +F P RFL                    E   D R C \nSbjct  281  TTAMVNMWAITHDPKVW-KDPVEFKPERFL--------------------EAEVDVRGCD  319\n\nQuery  481  FVLKDPNKNPAFLPFGSGARACVGQKFVTQGVATLFASLLEQYE  524\n              L          PFG+G R C G+      V    A L++ ++\nSbjct  320  LRLA---------PFGAGRRVCPGKNLGLVTVQLWVAKLMQGFK  354\n\n',
        gaps: '19',
        identities: '26'
      },
      {
        subjectName: 'Ghir_D03G004680.1 unnamed protein product',
        subjectLength: '537',
        score: '89.4',
        eValue: '4e-18',
        positives: '40',
        pairSequence:
          'Query  38   AFLWISLITITYFLSYKLFKLFKLWNQACKIPGPPSPSFYGYFTTLSK----QNLTEVLS  93\n            AFL I+L +  + +    +K  +  N    IPGP     +G   TLS+    ++L  +  \nSbjct  38   AFLSIALFSWAFAVGGIAWKNGRNRNGTLPIPGPRGFPVFGSLFTLSRGLAHRSLAAMAW  97\n\nQuery  94   DSHEEYGSIVKLWLSPKQLLVSIKEPEIIKEMLLKAK--DKLPLTGKAFNLAFGRSTLFA  151\n                       L  +P   +V   +P   +E+L      D+ P+   A +L F R+  FA\nSbjct  98   SRANTQLMAFSLGSTP---VVVASDPHTAREILTSPHFADR-PIKQSAKSLMFSRAIGFA  153\n\nQuery  152  SSFDKVESRRESLASELNV--RLLDRA---NLIATKAVDHIMAE--LHQNMTKGSINCKM  204\n             +       R   +S L    R+L       L  T  + +I  E  LH     GS+  + \nSbjct  154  PNGTHWRLLRRIASSHLFAPKRILAHEPGRQLDCTVMLRNIANEQKLH-----GSVCLRK  208\n\nQuery  205  TSQHMAFTLLGATIFGDTFLAWLKSTIYEELLMMVAK-----------DACFWASYSVIP  253\n              Q  A   +  ++FG  +     S   EEL  MV +           D   W SY   P\nSbjct  209  HLQFAALNNIMGSVFGRRYDQRKDSEELEELRDMVREGFELLGAFNWSDYLPWLSYFYDP  268\n\nQuery  254  FWKQGFWRYRRLCTELKWLTQDLVQQCSKYRQYRHMEPSANLGMEAGVFLQDNISLQEIN  313\n            F      R  + C +L    + LV+      Q+R +  S  L   A  F+   +SL   +\nSbjct  269  F------RINQRCLQLVPRVRKLVKGI--IEQHRQLSKSKMLSDNAD-FVDVLLSL---D  316\n\nQuery  314  GRHNVR-DESCGNIMSLLFHGCLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKKGSEDK  372\n            G   ++ D+    +  ++F G  TT  L   ++  LV HPE+Q K+  EI  A + ++  \nSbjct  317  GEEKLQEDDMVAVLWEMIFRGTDTTALLTEWVMAELVLHPEVQAKLQLEIDSATR-NKTL  375\n\nQuery  373  AQPVVEKMPLLWATIYESARVMPAGPLLQRCSLK-HDLRLKSGVIVPAGAILVVPMQLVQ  431\n                V K+P L A + E+ R+ P GPLL    L   D++L +G++VPA    +V M  + \nSbjct  376  TDADVAKLPYLQAVVKETLRIHPPGPLLSWARLSTSDVQLSNGMLVPANTTAMVNMWAIT  435\n\nQuery  432  TDDSSWGNDAGKFNPYRFLSKTEKTSASPNMDASIAGHAEELKDQRKCTFVLKDPNKNPA  491\n             D   W  D  +F P RFL            +A +     +L+                 \nSbjct  436  HDPKVW-KDPVEFKPERFL------------EAEVDVRGGDLR-----------------  465\n\nQuery  492  FLPFGSGARACVGQKFVTQGVATLFASLLEQYE  524\n              PFG+G R C G+      V    A L++ ++\nSbjct  466  LAPFGAGRRVCPGKNLGLVTVQLWVAKLMQGFK  498\n\n',
        gaps: '15',
        identities: '25'
      },
      {
        subjectName: 'Ghir_A04G015150.1 unnamed protein product',
        subjectLength: '432',
        score: '88.6',
        eValue: '4e-18',
        positives: '43',
        pairSequence:
          'Query  103  VKLWLSPKQLLVSIKEPEIIKEMLL-KAKDKLPLTGKAFNLAFGRSTLFASSFDKVESRR  161\n            +K  L   ++++S   P+  KE+L   A    P+   A +L F R+  FA S       R\nSbjct  1    MKFSLGATRVIIS-SHPDTAKEILGGSAFSDRPIKDSARSLMFERAIGFAPSGAYWRHLR  59\n\nQuery  162  ESLASEL--NVRLLDRANLIATKAVDHIMAELHQNM-TKGSINCKMTSQHMAFTLLGATI  218\n               A+ +    R+L+   L   + V+H++ +  + M TKG +  +M  Q  + T +  T+\nSbjct  60   RIAANHMFSPKRILNLEPL-RQQVVNHMVVQTQRAMETKGFVELRMILQKGSLTNILETV  118\n\nQuery  219  FGDTFLAWLKSTIYEELLMMVAKD----ACF-WASYSVIPFWKQGFWRYRRLCTELKWLT  273\n            FG    ++L S + +EL +MV +     A F W  +  + F    F   +R C +L    \nSbjct  119  FG----SFLSSAMADELGLMVKEGYELIAMFNWEDHFPVRFLD--FNGVKRRCHKLSNKV  172\n\nQuery  274  QDLVQQCSKYRQYRHMEPSANLGMEAGVFLQDNISLQEINGRHNVRDESCGNIMSLLFHG  333\n            + +V +  + R+   ++ S N G     FL   ++L + +   +   +    +  ++F G\nSbjct  173  KIVVGRIVEERRKEALDQSINGGNHD--FLTALLTLSKEDQLSD--SDMIAVLWEMIFRG  228\n\nQuery  334  CLTTGGLINNMLMRLVTHPEIQHKIYSEIIMAKKGSEDKA--QPVVEKMPLLWATIYESA  391\n              T   L+  ++ R+V H +IQ K+  EI       +D       +  +P L A + E  \nSbjct  229  TDTVAILLEWIMARMVLHQDIQAKVQEEIDSCISHRDDHCVHDSNLPNLPYLQAVVKEVL  288\n\nQuery  392  RVMPAGPLLQRCSLK-HDLRLKSGVIVPAGAILVVPMQLVQTDDSSWGNDAGKFNPYRFL  450\n            R+ P GPLL    L  HD+ +    I PAG   +V M  +  D S W  D   F P RF+\nSbjct  289  RLHPPGPLLSWARLAIHDVHIGKSFI-PAGTTAMVNMWAITHDPSIW-KDPWTFRPERFI  346\n\nQuery  451  SKTEKTSASPNMDASIAGHAEELKDQRKCTFVLKDPNKNPAFLPFGSGARACVGQKFVTQ  510\n             +          D SI G      D R                PFGSG R C G+     \nSbjct  347  EE----------DVSIMG-----SDLR--------------LAPFGSGRRVCPGKALGLA  377\n\nQuery  511  GVATLFASLLEQYE  524\n             V    A LL+ ++\nSbjct  378  TVQLWLARLLQSFK  391\n\n',
        gaps: '13',
        identities: '26'
      }
    ]
  },
  {
    query: 'CYP78A7',
    queryLength: '559',
    alignments: []
  }
]
